---
pagetitle: "About this tracker"
output: 
  html_document: 
    anchor_sections: false
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'about_tracker.html'))})
---

<h2 style="text-align:center;">About this tracker</h2>

<hr style="width:50%;text-align:center;">

<br>

This website seeks to serve as a sort of tracker for monitoring Indonesia's path to recovery from the COVID-19 pandemic. To that end, it puts together economic indicators comprising GDP, inflation, poverty rate, unemployment rate, consumer confidence, retail sales and movement trends. It also adds data on the coronavirus pandemic. The data for these indicators are all publicly accessible, but are scattered across websites.

Although this website does not cover all available economic indicators, it uses data from multiple sources that are both timely and relevant to give a glimpse of what is going on in the economy as the pandemic unfolds.

This website mainly seeks to provide a tool for people wanting to casually keep tabs on Indonesia's recovery from the pandemic without getting too caught up in it.  

If you find a bug, please report it [here](https://github.com/dzulfiqarfr/indonesia-recovery-tracker/issues). You can also offer a suggestion through [Twitter](https://twitter.com/dzulfiqarfr).