---
pagetitle: "Data"
output: 
  html_document: 
    anchor_sections: false
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'dataset.html'))})
---

<h2 style="text-align:center;">Data</h2>

<hr style="width:50%;text-align:center;">

<br>

This website uses publicly available data that can be found on the website of its respective sources. But you can also download some of datasets [here](https://github.com/dzulfiqarfr/indonesia-recovery-tracker/tree/main/data).

<br>  

<div class="panel panel-default">
  <div class="panel-heading"><h5>GDP</h5></div>
  <div class="panel-body">  
This website uses data on the year-on-year (yoy) percent change of quarterly GDP in constant 2010 prices for the economic growth indicator. The data on growth by sectors is accessible through the Dynamic Table feature on Statistics Indonesia's (BPS) website.

The projection for this year's economic growth is obtained from the World Bank.

<b>Source</b>: [BPS](https://bps.go.id/indicator/169/108/1/-seri-2010-laju-pertumbuhan-pdb-seri-2010-menurut-pengeluaran.html); [World Bank](https://www.worldbank.org/en/news/press-release/2020/12/17/indonesia-support-for-public-health-and-affected-households-and-firms-critical-for-a-secure-and-fast-recovery)    

<b>Last updated</b>: a) BPS: Nov 5, 2020; b) World Bank: Dec 17, 2020
  </div>
</div>

<br>

<div class="panel panel-default">
  <div class="panel-heading"><h5>Inflation</h5></div>
  <div class="panel-body">  
This website uses data on the year-on-year (yoy) percent change of the consumer price index (CPI) with 2018 as the base year from BPS for the inflation indicator.

The projection for this year's inflation rate is obtained from the World Bank.

<b>Source</b>: [BPS](https://www.bps.go.id/statictable/2014/09/26/915/tingkat-inflasi-tahun-ke-tahun-gabungan-90-kota-sup-1-sup-2018-100-.html); [World Bank](https://www.worldbank.org/en/news/press-release/2020/12/17/indonesia-support-for-public-health-and-affected-households-and-firms-critical-for-a-secure-and-fast-recovery)  

<b>Last updated</b>: a) BPS: Jan 4, 2021; b) World Bank: Dec 17, 2020
  </div>
</div>

<br>

<div class="panel panel-default">
  <div class="panel-heading"><h5>Unemployment</h5></div>
  <div class="panel-body">  
This website uses data on unemployment rate based on the National Labor Force Survey (Sakernas) from BPS. The agency carries out the survey on February and August.

The projection for unemployment rate in 2020 is obtained from the government.

<b>Source</b>: [BPS](https://www.bps.go.id/indicator/6/543/1/tingkat-pengangguran-terbuka-menurut-provinsi.html); [National Development Planning Minister (Bappenas)](https://www.thejakartapost.com/news/2020/06/22/govt-expects-unemployment-to-worsen-continue-into-next-year.html)

<b>Last updated</b>: a) BPS: Nov 5, 2020; b) Bappenas: June 22, 2020
  </div>
</div>

<br>

<div class="panel panel-default">
  <div class="panel-heading"><h5>Poverty</h5></div>
  <div class="panel-body">  
This website uses data on poverty rate based on the National Social and Economic Survey (Susenas) from BPS. The survey conducted in March takes a sample of 300,000 households, while the one in September 75,000 households.

The projection for poverty rate in 2020 is obtained from SMERU Research Institute.

<b>Source</b>: [BPS](https://www.bps.go.id/indicator/23/192/1/persentase-penduduk-miskin-menurut-provinsi.html); [SMERU Rsearch Institute](https://smeru.or.id/id/content/dampak-pandemi-covid-19-terhadap-kemiskinan-estimasi-bagi-indonesia)

<b>Last updated</b>: a) BPS: July 17, 2020; b) SMERU: April 2020
  </div>
</div>

<br>

<div class="panel panel-default">
  <div class="panel-heading"><h5>Consumer confidence</h5></div>
  <div class="panel-body">  
This website uses data on consumer confidence index for the consumer confidence indicator. The consumer confidence index is obtained from a monthly survey. It is the arithmentic mean of the current economic condition index and consumer expectation index.

Index points above the 100 threshold suggest that optimistic responses outweigh the pessimistic ones and index points below the threshold suggest the opposite.

<b>Source</b>: [Bank Indonesia (BI)](https://www.bi.go.id/id/publikasi/laporan/Pages/SK-Desember-2020.aspx)

<b>Last updated</b>: Jan 11, 2021
  </div>
</div>

<br>

<div class="panel panel-default">
  <div class="panel-heading"><h5>Retail sales</h5></div>
  <div class="panel-body">  
This website uses data on retail sales index for the retail sales indicator. The retail sales index is obtained from a monthly survey on 700 retailers in 10 big cities. It is the comparison between total sales in a given month and the total sales in January 2010 as the base period. 

<b>Source</b>: [BI](https://www.bi.go.id/id/publikasi/laporan/Pages/SPE-November-2020.aspx)  

<b>Last updated</b>:  Jan 12, 2021  
  </div>
</div>

<br>  

<div class="panel panel-default">
  <div class="panel-heading"><h5>Mobility</h5></div>
  <div class="panel-body">  
This website uses data on the number of visitors by place categories for the mobility indicator. The headline numbers represent the change in the number of visitors relative to the median level in the January 3--February 6 period.

<b>Source</b>: [Google](https://www.google.com/covid19/mobility/index.html?hl=en) 

<b>Last updated</b>: `r format(Sys.time(), "%b %d, %Y")`
  </div>
</div>

<br>  

<div class="panel panel-default">
  <div class="panel-heading"><h5>COVID-19</h5></div>
  <div class="panel-body">  
This website uses data on the number of confirmed cases and deaths from the Indonesian government, as well as testing from Our World in Data.

The positive rate is the number of confirmed cases divided by the number of tests. The [World Health Organization (WHO)](https://www.who.int/docs/default-source/coronaviruse/transcripts/who-audio-emergencies-coronavirus-press-conference-full-30mar2020.pdf?sfvrsn=6b68bc4a_2) considered the positive rate of 10 percent to be the general benchmark of enough testing to find all cases.

<b>Source</b>: [Indonesian government](https://data.covid19.go.id/public/api/update.json); [Our World in Data](https://github.com/owid/covid-19-data/blob/master/public/data/testing/covid-testing-all-observations.csv) 

<b>Last updated</b>: `r format(Sys.time(), "%b %d, %Y")`
  </div>
</div>