---
pagetitle: "Indonesia COVID-19 Recovery Tracker"
output: 
  html_document: 
    anchor_sections: false
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

<h2 style="text-align:center;">Tracking Indonesia’s recovery<br>from COVID-19</h2>

<hr style="width:50%;text-align:center;">

```{r setup, echo = F, message = F, warning = F}
# r markdown global options
knitr::opts_chunk$set(
  echo = F,
  message = F,
  warning = F
)

# packages
library(crosstalk)
library(htmltools)

# api
BPS_KEY <- Sys.getenv("BPS_KEY")
```

```{r}
source("script/summary_script.R", local = knitr::knit_global())

gt_summary
```

<hr>  

## Explore {.tabset .tabset-pills}  
<hr style="width:6%;text-align:left;margin-left:0;background-color:#263238;height:4px">

<br>  

### GDP {.tabset}

#### Headline

```{r growth plot}
source(
  "script/gdp_headline_script.R", 
  local = knitr::knit_global()
)

div(
  h4(strong("Sign of recovery after recession")),
  h5("GDP (percent change from a year earlier)"),
  bscols(growth_plot, widths = 12),
  "Chart: @dzulfiqarfr | Source: Statsitics Indonesia (BPS)"
)
```

#### Expenditure

```{r growth by expenditure table}
growth_table
```


#### Sectors

```{r growth by sectors table}
source(
  "script/growth-sectors_script.R", 
  local = knitr::knit_global()
)

sectors_gt
```


#### Contribution to growth

```{r ctg plot}
source("script/gdp_ctg_script.R", local = knitr::knit_global())

div(
  h4(strong("Contraction in main drivers")),
  h5(
    "GDP, contribution to growth by expenditure",  
    br("(percent change from a year earlier)")
  ),
  bscols(ctg_plot, widths = 12),
  "Chart: @dzulfiqarfr | Source: Statsitics Indonesia (BPS)"
)
```


### Consumer confidence

```{r CCI plot}
source("script/cci_script.R", local = knitr::knit_global())

div(
  h4(strong("Consumer pessimism returns")),
  h5("Consumer confidence index"),
  bscols(CCI_plot, widths = 12),
  "Chart: @dzulfiqarfr | Source: Bank Indonesia"
)
```


### Retail sales

```{r SPE plot}
source("script/spe_script.R", local = knitr::knit_global())

div(
  h4(strong("Upward blip")),
  h5("Retail sales index*, January 2010 = 100"),
  h6("(percent change on a year earlier)"),
  bscols(SPE_plot, widths = 12),
  str_c(
    "*", 
    format(last(SPE_tidy$Year), "%B %Y"),
    " figure is an estimate"
  ),
  br("Chart: @dzulfiqarfr | Source: Bank Indonesia")
)
```


### Mobility {.tabset}

#### National

```{r national mobility plot}
source("script/mobility_script.R", local = knitr::knit_global())

div(
  h4(strong("Mobility trends in Indonesia")),
  h5(
    "Number of visitors, by place categories",
    br("(percent change from Jan-Feb period, 7-day moving average)")
  ),
  bscols(mob_ntl_plot, widths = 12),
  str_c("Last updated on ", Sys.Date()),
  br("Chart: @dzulfiqarfr | Source: Google")
)
```

#### Regional

```{r regional mobility plot}
div(
  h4(strong("Mobility trends across provinces")),
  h5(
    "Number of visitors, by place categories",
    br("(percent change from Jan-Feb period, 7-day moving average)")
  ),
  bscols(
    mob_prov_fil,
    mob_prov_plot,
    widths = c(12, 12)
  ),
  str_c("Last updated on ", Sys.Date()),
  br("Chart: @dzulfiqarfr | Source: Google")
)
```

```{js set default value for regional mobility plot}
function filter_default() {
    document.getElementById("Province_filter").getElementsByClassName("selectized")[0].selectize.setValue("Jakarta");
}
window.onload = filter_default;
```

### COVID-19 {.tabset}

#### Cases

```{r covid-19 cases plot}
source(
  "script/cov-case-death_script.R", 
  local = knitr::knit_global()
)

div(
  h4(strong("Daily new cases")),
  h5("Number of confirmed cases per day"),
  bscols(case_plot, widths = 12),
  str_c("Last updated on ", Sys.Date()),
  br("Chart: @dzulfiqarfr | Source: Statsitics Indonesia (BPS)")
)
```

#### Deaths

```{r covid-19 deaths plot}
div(
  h4(strong("Daily new deaths")),
  h5("Number of confirmed deaths per day"),
  bscols(death_plot, widths = 12),
  str_c("Last updated on ", Sys.Date()),
  br("Chart: @dzulfiqarfr | Source: Statsitics Indonesia (BPS)")
)
```

#### Testing

```{r test plot}
source("script/cov_testing_script.R", local = knitr::knit_global())

div(
  h4(strong("COVID-19 tests")),
  bscols(
    widths = c(6, 6),
    div(
      h5("Cumulative tests", br("(in million)")),
      test_plot
    ),
    div(
      h5("Cumulative positive rate", br("(in percent)")),
      pos_rate_plot
    )
  ),
  str_c("Last updated on ", Sys.Date()),
  br("Chart: @dzulfiqarfr | Source: Our World in Data; Indonesian government")
)
```

