name: Daily update

on:
  schedule:
    - cron:  '30 8-10 * * *'
  push:
    branches:
      - main

jobs:
  render:
    name: Daily update
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Cache renv packages
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
      - name: Render website
        env:
          BPS_KEY: ${{ secrets.BPS_KEY }}
        run: |
          BPS_KEY <- Sys.getenv("BPS_KEY")
          rmarkdown::render_site()
        shell: Rscript {0}
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
      - name: Commit results to main branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "Daily update" || echo "No changes to commit"
          git push origin || echo "No changes to commit"